# Generated by Django 4.1.2 on 2023-05-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategories_name', models.CharField(max_length=500)),
                ('category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='Categories.categories')),
            ],
        ),
    ]
